### ISSUE TITLE
Restructure Experiment Options [Admin Area]

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/ExplorViz#1]
Create an own visual group for experiment options (see red box in screenshot) and add short description (e.g. hover)

![untitled](https://cloud.githubusercontent.com/assets/12273570/11265849/fa15472a-8e9f-11e5-9163-55f5cfc6b8e3.png)

**Comment by czirkelbach** [comment]
Restructured settings and improved usability by addings explainations for the available options.
![untitled](https://cloud.githubusercontent.com/assets/12273570/11271694/0287c6da-8ec8-11e5-8304-d03e61a2fae9.png)

**Comment by czirkelbach** [comment]
ToDo: 
- read curently saved configuration to show the current settings in the formular.
- Get feedback when saving the configuration (e.g., successful or not)

**Comment by Alexander-Krause** [comment]
Almost done in experiment-improvements branch. Skip flag is not implemented yet. Consider adding skip flag for every questionnaire in "Experiment Tools -> Edit Questionnaire".

**Comment by czirkelbach** [comment]
Close issue because of deprecated repository.
