### ISSUE TITLE
Rift Runtime 1.3 support via WebVR

### ISSUE THREAD

**Issue by Alexander-Krause** [ExplorViz/ExplorViz#3]
Make direct mode available for ExplorViz via WebVR.

[Current WebVR blog post](http://blog.tojicode.com/2016/02/moving-towards-webvr-10.html)
[Information for direct mode in WebVR 1](https://www.reddit.com/r/WebVR/comments/3g871k/will_the_lack_of_extended_mode_in_oculus_drivers/?)
[Information for direct mode in WebVR 1](https://www.reddit.com/r/oculus/comments/3g7ql3/oculus_sdk_v07_and_webvr_adaptation/)

**Comment by Alexander-Krause** [comment]
Rift DK2 works now with newest Chromium Build and Oculus runtime v1.3 (= Oculus Home). Oculus Home listens for external applications, i.e. ExplorViz. Thus it must run at any time. CV1 should work as well.

- [ ] Refactor positional tracking

**Comment by czirkelbach** [comment]
Close issue because of deprecated repository.
